version: "3"

networks:
  bunny:
     driver: bridge
     ipam:
       driver: default
       config:
          - subnet: 172.23.0.0/24

services:
  rpc_client:
     build: ./simulator
     image: simulator
     entrypoint: /bin/bash  /messaging/client.sh
     networks:
       bunny:
         ipv4_address: 172.23.0.9
     environment:
        - topics=1
        - servers=1
        - messages=3000
        - timeout=60
        - threads=32
        - sync=call

     depends_on:
        - rpc_server
        - influxdb

  rpc_server:
     build: ./simulator
     image: simulator
     entrypoint: /bin/bash /messaging/server.sh

     networks:
       bunny:
         ipv4_address: 172.23.0.12

     environment:
       - topic=1
       - server=1

     depends_on:
       - pm-1
       - influxdb

  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    networks:
      bunny:
        ipv4_address: 172.23.0.10

  pm-1:
    build: ./pacemaker
    image: pacemaker
    container_name: pm-1
    hostname: pm-1
    command: /bin/bash /docker/start.sh
    cap_add:
       - NET_ADMIN
       - SYS_ADMIN
    environment:
      cluster_password: r00tme
    networks:
      bunny:
        ipv4_address: 172.23.0.6

  pm-2:
    build: ./pacemaker
    image: pacemaker
    container_name: pm-2
    hostname: pm-2
    command: /bin/bash /docker/start.sh
    cap_add:
       - NET_ADMIN
       - SYS_ADMIN
    environment:
      cluster_password: r00tme
    networks:
      bunny:
        ipv4_address: 172.23.0.7

  pm-3:
    build: ./pacemaker
    image: pacemaker
    container_name: pm-3
    hostname: pm-3
    command: /bin/bash /docker/start.sh
    cap_add:
       - NET_ADMIN
       - SYS_ADMIN
    environment:
      cluster_password: r00tme
    networks:
      bunny:
        ipv4_address: 172.23.0.8
